### ISSUE TITLE
Docker starts, but joola cannot be reached.

### ISSUE THREAD

**Issue by felixW** [joola/joola#653]
Everything is up, but no answer from https://localhost:8081/.
Running on latest versions of Docker and Joola.
![image](https://cloud.githubusercontent.com/assets/57482/6005515/b0d31e40-ab13-11e4-88a9-33aeec0c28b2.png)

**Comment by itayw** [comment]
Hi @felixW, our docker support is a bit behind, I'll rebase it later tonight/tomorrow morning and let you know if there are any issues with the latest version.

**Comment by itayw** [comment]
@felixW Can you please try pulling a fresh docker image and try again? Please note two small changes:
- I changed the README to point at `localhost:8080` instead of 8081, this is to avoid a certificate issue.
- There's an unrelated issue with the Canvas on the main welcome page, so please also try accessing [`http://localhost:8080/play/canvas.html`](http://localhost:8080/play/canvas.html)

Let me know how it goes.

**Comment by felixW** [comment]
Working great! thanks!
